import 'dart:convert';

import 'package:excel_plus/excel_plus.dart';
import 'package:test/test.dart';

/// A blank workbook plus its default sheet, ready to fill.
(Excel, Sheet) _blank() {
  final excel = Excel.createExcel();
  return (excel, excel[excel.getDefaultSheet()!]);
}

/// A sheet holding a `name,age,active` header and two data rows.
(Excel, Sheet) _people() {
  final (excel, sheet) = _blank();
  sheet.appendRow([
    TextCellValue('name'),
    TextCellValue('age'),
    TextCellValue('active'),
  ]);
  sheet.appendRow([
    TextCellValue('Alice'),
    IntCellValue(30),
    BoolCellValue(true),
  ]);
  sheet.appendRow([
    TextCellValue('Bob'),
    IntCellValue(25),
    BoolCellValue(false),
  ]);
  return (excel, sheet);
}

void main() {
  group('Header-Keyed Rows', () {
    test('keys each data row by the first row and omits the header', () {
      final (_, sheet) = _people();

      expect(sheet.rowsAsMaps(), [
        {'name': 'Alice', 'age': 30, 'active': true},
        {'name': 'Bob', 'age': 25, 'active': false},
      ]);
    });

    test('keeps native Dart types for numbers and booleans', () {
      final (_, sheet) = _blank();
      sheet.appendRow([TextCellValue('i'), TextCellValue('d')]);
      sheet.appendRow([IntCellValue(7), DoubleCellValue(1.5)]);

      final row = sheet.rowsAsMaps().single;
      expect(row['i'], isA<int>().having((v) => v, 'value', 7));
      expect(row['d'], isA<double>().having((v) => v, 'value', 1.5));
    });

    test('renders dates, times, and errors as strings', () {
      final (_, sheet) = _blank();
      sheet.appendRow([
        TextCellValue('date'),
        TextCellValue('stamp'),
        TextCellValue('clock'),
        TextCellValue('err'),
      ]);
      sheet.appendRow([
        DateCellValue(year: 2024, month: 1, day: 31),
        DateTimeCellValue(
          year: 2024,
          month: 1,
          day: 31,
          hour: 9,
          minute: 30,
          second: 0,
        ),
        TimeCellValue(hour: 9, minute: 30, second: 15),
        CellErrorValue.divisionByZero,
      ]);

      expect(sheet.rowsAsMaps().single, {
        'date': '2024-01-31',
        'stamp': '2024-01-31T09:30:00',
        'clock': '09:30:15',
        'err': '#DIV/0!',
      });
    });

    test('gives every map the same keys, with null for an empty cell', () {
      final (_, sheet) = _blank();
      sheet.appendRow([TextCellValue('a'), TextCellValue('b')]);
      sheet.appendRow([TextCellValue('x')]);

      final row = sheet.rowsAsMaps().single;
      expect(row.keys, ['a', 'b']);
      expect(row['b'], isNull);
    });

    test('falls back to the column letter for an empty header cell', () {
      final (_, sheet) = _blank();
      sheet.appendRow([TextCellValue('a'), null, TextCellValue('c')]);
      sheet.appendRow([
        TextCellValue('1'),
        TextCellValue('2'),
        TextCellValue('3'),
      ]);

      expect(sheet.rowsAsMaps().single.keys, ['a', 'B', 'c']);
    });

    test('suffixes a repeated header name instead of dropping the column', () {
      final (_, sheet) = _blank();
      sheet.appendRow([
        TextCellValue('id'),
        TextCellValue('id'),
        TextCellValue('id'),
      ]);
      sheet.appendRow([IntCellValue(1), IntCellValue(2), IntCellValue(3)]);

      expect(sheet.rowsAsMaps().single, {'id': 1, 'id_2': 2, 'id_3': 3});
    });

    test('resolves a suffix that would collide with a literal header', () {
      final (_, sheet) = _blank();
      sheet.appendRow([
        TextCellValue('id'),
        TextCellValue('id_2'),
        TextCellValue('id'),
      ]);
      sheet.appendRow([IntCellValue(1), IntCellValue(2), IntCellValue(3)]);

      expect(sheet.rowsAsMaps().single.keys, ['id', 'id_2', 'id_3']);
    });

    test('takes the keys from a later row when headerRow is given', () {
      final (_, sheet) = _blank();
      sheet.appendRow([TextCellValue('generated by excel_plus')]);
      sheet.appendRow([TextCellValue('name'), TextCellValue('age')]);
      sheet.appendRow([TextCellValue('Alice'), IntCellValue(30)]);

      expect(sheet.rowsAsMaps(headerRow: 1), [
        {'name': 'Alice', 'age': 30},
      ]);
    });

    test('drops an all-empty row unless skipEmptyRows is false', () {
      final (_, sheet) = _blank();
      sheet.appendRow([TextCellValue('a')]);
      sheet.appendRow([TextCellValue('x')]);
      sheet.updateCell(CellIndex.indexByString('A4'), TextCellValue('y'));

      expect(sheet.rowsAsMaps().length, 2);
      expect(sheet.rowsAsMaps(skipEmptyRows: false).length, 3);
    });

    test('returns an empty list when the header row is past the last row', () {
      final (_, sheet) = _people();

      expect(sheet.rowsAsMaps(headerRow: 99), isEmpty);
    });

    test('rejects a negative header row', () {
      final (_, sheet) = _people();

      expect(() => sheet.rowsAsMaps(headerRow: -1), throwsArgumentError);
    });

    test('exports a formula as its cached result, or its text when asked', () {
      final (_, sheet) = _blank();
      sheet.appendRow([TextCellValue('total')]);
      sheet.updateCell(
        CellIndex.indexByString('A2'),
        FormulaCellValue('SUM(B1:B3)', cachedValue: '6'),
      );

      expect(sheet.rowsAsMaps().single['total'], '6');
      expect(
        sheet.rowsAsMaps(formulasAsText: true).single['total'],
        '=SUM(B1:B3)',
      );
    });
  });

  group('Sheet JSON Export', () {
    test('serialises to an array of header-keyed objects', () {
      final (_, sheet) = _people();

      expect(jsonDecode(sheet.toJson()), [
        {'name': 'Alice', 'age': 30, 'active': true},
        {'name': 'Bob', 'age': 25, 'active': false},
      ]);
    });

    test('serialises to an array of arrays when headerRow is null', () {
      final (_, sheet) = _people();

      expect(jsonDecode(sheet.toJson(headerRow: null)), [
        ['name', 'age', 'active'],
        ['Alice', 30, true],
        ['Bob', 25, false],
      ]);
    });

    test('indents the output when pretty is set', () {
      final (_, sheet) = _people();

      final pretty = sheet.toJson(pretty: true);
      expect(pretty, contains('\n  {\n'));
      expect(jsonDecode(pretty), jsonDecode(sheet.toJson()));
    });

    test('escapes quotes and newlines so the result stays valid JSON', () {
      final (_, sheet) = _blank();
      sheet.appendRow([TextCellValue('note')]);
      sheet.appendRow([TextCellValue('say "hi"\nagain')]);

      expect(jsonDecode(sheet.toJson()), [
        {'note': 'say "hi"\nagain'},
      ]);
    });

    test('serialises an empty sheet as an empty array', () {
      final (_, sheet) = _blank();

      expect(sheet.toJson(), '[]');
      expect(sheet.toJson(headerRow: null), '[]');
    });
  });

  group('Workbook JSON Export', () {
    test('keys every sheet by name in worksheet order', () {
      final (excel, _) = _people();
      final totals = excel['Totals'];
      totals.appendRow([TextCellValue('sum')]);
      totals.appendRow([IntCellValue(55)]);

      final decoded = jsonDecode(excel.toJson()) as Map<String, dynamic>;
      expect(decoded.keys, containsAll(<String>['Sheet1', 'Totals']));
      expect(decoded['Totals'], [
        {'sum': 55},
      ]);
    });

    test('serialises just one sheet when it is named', () {
      final (excel, _) = _people();

      expect(jsonDecode(excel.toJson(sheet: 'Sheet1')), [
        {'name': 'Alice', 'age': 30, 'active': true},
        {'name': 'Bob', 'age': 25, 'active': false},
      ]);
    });

    test('rejects a sheet name the workbook does not have', () {
      final (excel, _) = _people();

      expect(() => excel.toJson(sheet: 'Missing'), throwsArgumentError);
    });

    test('survives a save and reload round trip', () {
      final (excel, _) = _people();
      final before = excel.toJson();

      final reloaded = Excel.decodeBytes(excel.save()!);

      expect(reloaded.toJson(), before);
    });
  });
}
